apiVersion: plural.sh/v1alpha1
kind: Dependencies
metadata:
  description: ingress-nginx equinix setup
  version: 0.1.0
spec:
  dependencies:
  - name: equinix-bootstrap
    repo: bootstrap
    type: terraform
    version: '>= 0.1.1'
  providers:
  - equinix
