apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: rook
spec:
  selector:
    matchLabels: {}
  componentKinds:
  - group: v1
    kind: Service
  - group: networking.k8s.io
    kind: Ingress
  - group: cert-manager.io
    kind: Certificate
  - group: apps
    kind: StatefulSet
  - group: apps
    kind: Deployment
  - group: batch
    kind: CronJob
  - group: batch
    kind: Job
  descriptor:
    type: rook
    version: 0.1.7
    description: open source cloud-native storage orchestrator for Kubernetes
    icons:
    - src: https://plural-assets.s3.us-east-2.amazonaws.com/uploads/repos/d4a2c822-0481-4b30-880a-dfd6423a925a/rook.png?v=63809733605
    

    {{- if .Values.global }}
    {{- if .Values.global.application }}
    {{- if .Values.global.application.links }}
    links:
    {{ toYaml .Values.global.application.links | nindent 6 }}
    {{- end }}
  {{- if .Values.global.application.info }}
  info:
  {{ toYaml .Values.global.application.info | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- end }}
